"""auto phone

Revision ID: ccef7d94f4da
Revises: b3d424a431f3
Create Date: 2024-02-13 11:21:00.758792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccef7d94f4da'
down_revision: Union[str, None] = 'b3d424a431f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.add_column('users', sa.Column('phone', sa.String(), nullable=False, server_default=''))


    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
